const { Omit, Only } = require("./index")

const base = {
    name: 'Rizkiansyah',
    age: 35,
    feature: 'tall'
}

console.log("Omit")
console.log("---")
console.log("")
console.log("this should should return => { name: 'Rizkiansyah' }")
console.log(Omit(base, ['feature', 'age']))
console.log("---")
console.log("")
console.log("this should return => { name: 'Rizkiansyah', feature: 'tall' }")
console.log(Omit(base, ['age']))
console.log("---")
console.log("")
console.log("this should return => { }")
console.log(Omit(base, ['name', 'age', 'feature']))
console.log("---")
console.log("")
console.log("this should return => { feature: 'tall', age: 35 }")
console.log(Omit(base, 'name'))
console.log("---")
console.log("")
console.log("")

console.log("Only")
console.log("---")
console.log("")
console.log("this should return => { age: 35, feature: 'tall' }")
console.log(Only(base, ['feature', 'age']))
console.log("---")
console.log("")
console.log("this should return => { age: 35 }")
console.log(Only(base, ['age']))
console.log("---")
console.log("")
console.log("this should return => { name: 'Rizkiansyah', age: 35, feature: 'tall' }")
console.log(Only(base, ['name', 'age', 'feature']))
console.log("---")
console.log("")
console.log("this should return => { name: 'Rizkiansyah' }")
console.log(Only(base, 'name'))
console.log("---")
console.log("")
console.log("Basic test done...")